import React from 'react'
import { storiesOf } from '@storybook/react'
import '../src/styles/style.scss'

import { Button } from '@storybook/react/demo'
import Test from '../src/components/Test'

storiesOf('Button', module)
    .add('with next', () => (
        <Button>Some text</Button>
    ))
    .add('with some emoji', () => (
        <Button><span role="image" aria-label="so cool">😀 😎 👍 💯</span></Button>
    ))
    .add("a new autogenerated button", () => (
        <Button>A new button</Button>
    ))

storiesOf('Test', module)
      .add('Test', () => (
        <Test data />
      ))